remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

body {
    font: unset;
    color: #000000;
}

header {   
    background: #000000; 
    h1 {
        color: #D8AB4C;
    }
}

#banner { 
    background: #D8AB4C;
}
